image: python:3.8-buster ## MkDocs requies python.

pages:
  stage: deploy ## tell GitLab to deploy the website in this step.
  before_script:
    - pip install mkdocs mkdocs-awesome-pages-plugin mkdocs-bootswatch ## install requirements.
  script:
    - cd ./src
    - mkdocs build ## built the site.
    - mv site ../public
  artifacts:
    paths:
    - public
