site_name: west
site_favicon: static/img/icon.png

theme: 
  name: lux
  custom_dir: custom_theme/

plugins:
  - awesome-pages


nav:
    - Home: 'index.md'
    - Projects:
      - Battery Tester: 'docs/external/BatteryTester/README.md'
    - CV: 'cv.md'
    - Gitlab: 'https://gitlab.com/jobbe97'
